# Generated by Django 4.2.13 on 2025-12-07 16:55

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('superadmin', 'Superadmin'), ('super_coordinador', 'Super Coordinador'), ('franquicia_admin', 'Administrador de Franquicia'), ('oficina_admin', 'Administrador de Oficina'), ('responsable', 'Responsable de Oficina'), ('coordinador', 'Coordinador'), ('comercial', 'Comercial')], default='comercial', max_length=32)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(db_index=True)),
                ('fecha_fin', models.DateTimeField(db_index=True)),
                ('tipo', models.CharField(choices=[('Contacto genérico', 'Contacto genérico'), ('Llamada genérica', 'Llamada genérica'), ('Contacto directo', 'Contacto directo'), ('Llamada de contacto directo', 'Llamada de contacto directo'), ('Cita de adquisición', 'Cita de adquisición'), ('Llamada de adquisición', 'Llamada de adquisición'), ('Contacto de adquisición', 'Contacto de adquisición'), ('Cita de seguimiento de encargo', 'Cita de seguimiento de encargo'), ('Llamada de seguimiento de encargo', 'Llamada de seguimiento de encargo'), ('Llamada de seguimiento de pedido', 'Llamada de seguimiento de pedido'), ('Contacto de seguimiento de pedido', 'Contacto de seguimiento de pedido'), ('Visita', 'Visita'), ('Reserva', 'Reserva'), ('Propuesta', 'Propuesta'), ('Aceptación de la propuesta', 'Aceptación de la propuesta'), ('Firma contrato de arras', 'Firma contrato de arras'), ('Escritura de compraventa', 'Escritura de compraventa')], db_index=True, default='Contacto genérico', max_length=50)),
                ('descripcion_empleado', models.TextField(blank=True, default='', null=True)),
                ('descripcion_publica', models.TextField(blank=True, default='', null=True)),
                ('estado', models.CharField(choices=[('Realizada', 'Realizada'), ('No realizada', 'No realizada'), ('En proceso', 'En proceso')], db_index=True, default='En proceso', max_length=20)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['-fecha_inicio', '-fecha_ultima_modificacion'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Desconocido', max_length=50)),
                ('apellido1', models.CharField(default='Desconocido', max_length=50)),
                ('apellido2', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_apellido', models.CharField(db_index=True, default='', editable=False, max_length=120)),
                ('nombre_apellidos_completo', models.CharField(db_index=True, default='', editable=False, max_length=160)),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('NIF', 'NIF'), ('PASAPORTE', 'Pasaporte')], default='DNI', max_length=20)),
                ('num_identificacion', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('direccion', models.CharField(default='', max_length=255)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='O', max_length=1)),
                ('trato', models.CharField(choices=[('Sr.', 'Sr.'), ('Sra.', 'Sra.'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.')], default='Sr.', max_length=5)),
                ('info_adicional', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_movil', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('email_secundario', models.EmailField(blank=True, max_length=254, null=True)),
                ('dias_ultimo_contacto', models.PositiveIntegerField(default=0)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True, db_index=True)),
                ('actividades', models.ManyToManyField(blank=True, related_name='clientes_asociados', to='api.actividad')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_ultima_modificacion'],
            },
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_postal', models.CharField(db_index=True, default='00000', max_length=10)),
                ('provincia', models.CharField(db_index=True, default='Desconocida', max_length=100)),
                ('calle', models.CharField(default='', max_length=100)),
                ('numero_calle', models.CharField(default='S/N', max_length=10)),
                ('latitud', models.FloatField(db_index=True, default=0.0)),
                ('longitud', models.FloatField(db_index=True, default=0.0)),
                ('tipo_finca', models.CharField(choices=[('Residencial', 'Residencial'), ('Señorial', 'Señorial'), ('Industrial', 'Industrial'), ('Otro', 'Otro')], db_index=True, default='Residencial', max_length=20)),
                ('finca_vertical', models.BooleanField(default=True)),
                ('anio_construccion', models.PositiveIntegerField(blank=True, null=True)),
                ('numero_plantas', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True, db_index=True)),
                ('actividades', models.ManyToManyField(blank=True, related_name='edificios_asociados', to='api.actividad')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edificios_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_ultima_modificacion'],
            },
        ),
        migrations.CreateModel(
            name='Franquicia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='franquicias/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Franquicia',
                'verbose_name_plural': 'Franquicias',
            },
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('franquicia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oficinas', to='api.franquicia')),
            ],
            options={
                'verbose_name': 'Oficina',
                'verbose_name_plural': 'Oficinas',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacion', models.CharField(choices=[('comprar', 'Comprar'), ('alquiler', 'Alquiler'), ('traspaso', 'Traspaso')], db_index=True, default='comprar', max_length=20)),
                ('tipo_inmueble', models.CharField(blank=True, max_length=100, null=True)),
                ('subtipo_inmueble', models.CharField(blank=True, max_length=100, null=True)),
                ('prioridad', models.PositiveSmallIntegerField(db_index=True, default=3, help_text='0-5 (5 = máxima prioridad)')),
                ('fecha', models.DateField(auto_now_add=True, db_index=True)),
                ('fecha_limite', models.DateField(blank=True, db_index=True, null=True)),
                ('procedencia', models.CharField(blank=True, choices=[('zona', 'Zona'), ('informador', 'Informador'), ('agencia', 'Agencia'), ('escaparate', 'Escaparate'), ('red_agencias', 'Red de agencias'), ('web_propia', 'Web propia'), ('portales', 'Portales inmobiliarios'), ('redes_sociales', 'Redes sociales')], db_index=True, max_length=50, null=True)),
                ('estado_pedido', models.CharField(choices=[('cerrado', 'Cerrado'), ('en_gestion', 'En gestión'), ('en_visita', 'En visita'), ('negociacion_avanzada', 'Negociación avanzada')], db_index=True, default='en_gestion', max_length=30)),
                ('estado_negociacion', models.CharField(blank=True, choices=[('pre_negociacion', 'Pre-negociación'), ('reserva', 'Reserva'), ('aceptacion', 'Aceptación'), ('arras', 'Arras firmadas'), ('escritura', 'Escritura')], db_index=True, max_length=30, null=True)),
                ('ubicaciones', models.TextField(default='', help_text='Zonas de interés separadas por comas')),
                ('superficie_min', models.PositiveIntegerField(default=0)),
                ('superficie_max', models.PositiveIntegerField(default=0)),
                ('habitaciones', models.PositiveIntegerField(default=0)),
                ('banos', models.PositiveIntegerField(default=0)),
                ('estancias', models.PositiveIntegerField(default=0)),
                ('planta_min', models.PositiveIntegerField(default=0)),
                ('planta_max', models.PositiveIntegerField(default=10)),
                ('plazas_parking', models.PositiveIntegerField(default=0)),
                ('amueblado', models.BooleanField(default=False)),
                ('estado_inmueble', models.CharField(blank=True, choices=[('nuevo', 'Nuevo'), ('casi_nuevo', 'Casi nuevo'), ('muy_bien', 'Muy bien'), ('bien', 'Bien'), ('a_reformar', 'A reformar'), ('reformado', 'Reformado')], db_index=True, max_length=20, null=True)),
                ('exterior', models.BooleanField(default=True)),
                ('balcon', models.BooleanField(default=False)),
                ('terraza', models.BooleanField(default=False)),
                ('jardin', models.BooleanField(default=False)),
                ('ascensor', models.BooleanField(default=False)),
                ('sotano', models.BooleanField(default=False)),
                ('patio', models.BooleanField(default=False)),
                ('piscina', models.BooleanField(default=False)),
                ('mascotas', models.BooleanField(default=False)),
                ('calefaccion', models.BooleanField(default=False)),
                ('aire_acondicionado', models.BooleanField(default=False)),
                ('precio_min', models.PositiveIntegerField(db_index=True, default=0)),
                ('precio_max', models.PositiveIntegerField(db_index=True, default=0)),
                ('entrada', models.PositiveIntegerField(default=0)),
                ('cirbe', models.BooleanField(default=False)),
                ('asesorado', models.BooleanField(default=False)),
                ('info_financiacion', models.TextField(blank=True, null=True)),
                ('tipo_pago', models.CharField(blank=True, choices=[('contado', 'Al contado'), ('financiar', 'A financiar'), ('inversion', 'Inversión')], db_index=True, max_length=20, null=True)),
                ('rentabilidad_min', models.PositiveIntegerField(default=0)),
                ('rentabilidad_max', models.PositiveIntegerField(default=0)),
                ('motivacion', models.TextField(blank=True, null=True)),
                ('motivacion_cambio', models.TextField(blank=True, null=True)),
                ('notas_privadas', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('privacidad_firmada', models.BooleanField(default=False)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True, db_index=True)),
                ('actividades', models.ManyToManyField(blank=True, related_name='pedidos_asociados', to='api.actividad')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='api.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_creados', to=settings.AUTH_USER_MODEL)),
                ('franquicia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='api.franquicia')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='api.oficina')),
                ('ultima_modificacion_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_ultima_modificacion', '-fecha', '-prioridad'],
            },
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planta', models.CharField(db_index=True, default='0', max_length=10)),
                ('puerta', models.CharField(db_index=True, default='A', max_length=10)),
                ('interior', models.CharField(blank=True, max_length=6, null=True)),
                ('ref_catastral', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('direccion_busqueda', models.CharField(db_index=True, default='', editable=False, max_length=200)),
                ('estado_certificado', models.CharField(blank=True, choices=[('Presente', 'Presente'), ('Exento', 'Exento'), ('En trámite', 'En trámite')], default='En trámite', max_length=20, null=True)),
                ('emisiones_CO2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('consumo_energia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('habitaciones', models.PositiveIntegerField(default=1)),
                ('banos', models.PositiveIntegerField(default=1)),
                ('estancias', models.PositiveIntegerField(default=1)),
                ('balcon', models.BooleanField(default=False)),
                ('jardin', models.BooleanField(default=False)),
                ('nota_simple', models.BooleanField(default=False)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True, db_index=True)),
                ('ocupado_por', models.CharField(choices=[('No identificado', 'No identificado'), ('Inquilino', 'Inquilino'), ('Propietario', 'Propietario'), ('Vacío', 'Vacío')], db_index=True, default='No identificado', max_length=20)),
                ('dias_ultimo_contacto', models.PositiveIntegerField(default=0)),
                ('fecha_ultimo_contacto', models.DateField(blank=True, db_index=True, null=True)),
                ('fecha_ultima_venta_alquiler', models.DateField(blank=True, null=True)),
                ('zona_asignada', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('dia_zona', models.DateField(blank=True, null=True)),
                ('estado_CRM', models.CharField(choices=[('Por defecto', 'Por defecto'), ('Noticia', 'Noticia'), ('Encargo', 'Encargo')], db_index=True, default='Por defecto', max_length=20)),
                ('motivacion', models.CharField(blank=True, default='', max_length=255)),
                ('precio_pedido_cliente', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_valoracion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_encargo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_valoracion', models.DateField(blank=True, null=True)),
                ('necesidad_venta', models.CharField(blank=True, default='', max_length=255)),
                ('prioridad_noticia', models.PositiveIntegerField(db_index=True, default=0)),
                ('tipo_procedencia', models.CharField(blank=True, default='', max_length=255)),
                ('nota_inmueble', models.TextField(blank=True, null=True)),
                ('nota_noticia', models.TextField(blank=True, null=True)),
                ('comision', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fecha_inicio_encargo', models.DateField(blank=True, null=True)),
                ('fecha_fin_encargo', models.DateField(blank=True, null=True)),
                ('latitud', models.FloatField(blank=True, db_index=True, default=0.0, null=True)),
                ('longitud', models.FloatField(blank=True, db_index=True, default=0.0, null=True)),
                ('actividades', models.ManyToManyField(blank=True, related_name='inmuebles_asociados', to='api.actividad')),
                ('coinquilinos', models.ManyToManyField(blank=True, related_name='coalquileres', to='api.cliente')),
                ('copropietarios', models.ManyToManyField(blank=True, related_name='copropiedades', to='api.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inmuebles_creados', to=settings.AUTH_USER_MODEL)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.edificio')),
                ('franquicia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to='api.franquicia')),
                ('informadores', models.ManyToManyField(blank=True, related_name='inmuebles_informados', to='api.cliente')),
                ('inquilino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alquileres', to='api.cliente')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to='api.oficina')),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propiedades', to='api.cliente')),
                ('ultima_modificacion_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inmuebles_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_ultima_modificacion', 'edificio_id', 'planta', 'puerta'],
            },
        ),
        migrations.AddField(
            model_name='edificio',
            name='franquicia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edificios', to='api.franquicia'),
        ),
        migrations.AddField(
            model_name='edificio',
            name='oficina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edificios', to='api.oficina'),
        ),
        migrations.AddField(
            model_name='edificio',
            name='ultima_modificacion_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edificios_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='franquicia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='api.franquicia'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='oficina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='api.oficina'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultima_modificacion_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actividad',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cliente'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actividad',
            name='franquicia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='api.franquicia'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='inmueble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.inmueble'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='oficina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='api.oficina'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pedido'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='ultima_modificacion_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_modificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='franquicia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='api.franquicia'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='oficina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='api.oficina'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['franquicia', 'oficina'], name='api_pedido_franqui_fb6d34_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['cliente', 'fecha'], name='api_pedido_cliente_01cc7a_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado_pedido'], name='api_pedido_estado__500066_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado_negociacion'], name='api_pedido_estado__0cad6a_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['prioridad'], name='api_pedido_priorid_89fbe6_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['precio_min', 'precio_max'], name='api_pedido_precio__a21b6a_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['fecha_ultima_modificacion'], name='api_pedido_fecha_u_1db030_idx'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(check=models.Q(('superficie_min__lte', models.F('superficie_max'))), name='pedido_superficie_min_le_max'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(check=models.Q(('planta_min__lte', models.F('planta_max'))), name='pedido_planta_min_le_max'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(check=models.Q(('precio_min__lte', models.F('precio_max'))), name='pedido_precio_min_le_max'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('rentabilidad_max', 0), ('rentabilidad_min', 0)), ('rentabilidad_min__lte', models.F('rentabilidad_max')), _connector='OR'), name='pedido_rentabilidad_min_le_max_or_zero'),
        ),
        migrations.AddIndex(
            model_name='inmueble',
            index=models.Index(fields=['franquicia', 'oficina'], name='api_inmuebl_franqui_9a4155_idx'),
        ),
        migrations.AddIndex(
            model_name='inmueble',
            index=models.Index(fields=['edificio', 'planta', 'puerta'], name='api_inmuebl_edifici_2e0e33_idx'),
        ),
        migrations.AddIndex(
            model_name='inmueble',
            index=models.Index(fields=['estado_CRM'], name='api_inmuebl_estado__cf4e0a_idx'),
        ),
        migrations.AddIndex(
            model_name='inmueble',
            index=models.Index(fields=['ocupado_por'], name='api_inmuebl_ocupado_330ad7_idx'),
        ),
        migrations.AddIndex(
            model_name='inmueble',
            index=models.Index(fields=['zona_asignada'], name='api_inmuebl_zona_as_52b30f_idx'),
        ),
        migrations.AddIndex(
            model_name='inmueble',
            index=models.Index(fields=['fecha_ultima_modificacion'], name='api_inmuebl_fecha_u_defc3b_idx'),
        ),
        migrations.AddIndex(
            model_name='inmueble',
            index=models.Index(fields=['latitud', 'longitud'], name='api_inmuebl_latitud_a0b652_idx'),
        ),
        migrations.AddConstraint(
            model_name='inmueble',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('fecha_fin_encargo__isnull', True), ('fecha_inicio_encargo__isnull', True)), models.Q(('fecha_fin_encargo__isnull', True), ('fecha_inicio_encargo__isnull', False)), models.Q(('fecha_fin_encargo__isnull', False), ('fecha_inicio_encargo__isnull', False), ('fecha_inicio_encargo__lte', models.F('fecha_fin_encargo'))), _connector='OR'), name='inmueble_fechas_encargo_coherentes'),
        ),
        migrations.AddIndex(
            model_name='edificio',
            index=models.Index(fields=['franquicia', 'oficina'], name='api_edifici_franqui_986e98_idx'),
        ),
        migrations.AddIndex(
            model_name='edificio',
            index=models.Index(fields=['codigo_postal'], name='api_edifici_codigo__d5a0f7_idx'),
        ),
        migrations.AddIndex(
            model_name='edificio',
            index=models.Index(fields=['provincia'], name='api_edifici_provinc_4389a7_idx'),
        ),
        migrations.AddIndex(
            model_name='edificio',
            index=models.Index(fields=['tipo_finca'], name='api_edifici_tipo_fi_b1072b_idx'),
        ),
        migrations.AddIndex(
            model_name='edificio',
            index=models.Index(fields=['latitud', 'longitud'], name='api_edifici_latitud_f9d34b_idx'),
        ),
        migrations.AddIndex(
            model_name='edificio',
            index=models.Index(fields=['fecha_ultima_modificacion'], name='api_edifici_fecha_u_72b213_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['franquicia', 'oficina'], name='api_cliente_franqui_0cad4e_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nombre_apellido'], name='api_cliente_nombre__130cf0_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nombre_apellidos_completo'], name='api_cliente_nombre__b60095_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['email'], name='api_cliente_email_7c88db_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['telefono_movil'], name='api_cliente_telefon_7485d8_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['fecha_ultima_modificacion'], name='api_cliente_fecha_u_b22749_idx'),
        ),
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['franquicia', 'oficina'], name='api_activid_franqui_a5af5a_idx'),
        ),
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['tipo'], name='api_activid_tipo_c14070_idx'),
        ),
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['estado'], name='api_activid_estado_24fab6_idx'),
        ),
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['fecha_inicio'], name='api_activid_fecha_i_291865_idx'),
        ),
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['fecha_fin'], name='api_activid_fecha_f_5556aa_idx'),
        ),
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['fecha_ultima_modificacion'], name='api_activid_fecha_u_75e918_idx'),
        ),
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['cliente', 'fecha_inicio'], name='api_activid_cliente_654e8d_idx'),
        ),
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['inmueble', 'fecha_inicio'], name='api_activid_inmuebl_79c7b8_idx'),
        ),
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['pedido', 'fecha_inicio'], name='api_activid_pedido__4cab8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='actividad',
            constraint=models.CheckConstraint(check=models.Q(('fecha_inicio__lt', models.F('fecha_fin'))), name='actividad_fecha_inicio_menor_que_fin'),
        ),
    ]
