# Generated by Django 4.2.13 on 2025-12-08 09:50

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_trgm_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='franquicia',
            options={'ordering': ['nombre'], 'verbose_name': 'Franquicia', 'verbose_name_plural': 'Franquicias'},
        ),
        migrations.AlterModelOptions(
            name='oficina',
            options={'ordering': ['franquicia_id', 'nombre'], 'verbose_name': 'Oficina', 'verbose_name_plural': 'Oficinas'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        
        migrations.AddField(
            model_name='cliente',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),

        # ------------------------------------------------------------
        # REMOCIÓN DE ÍNDICES AUTOMÁTICOS
        # ------------------------------------------------------------
        migrations.RemoveIndex(
            model_name='actividad',
            name='api_activid_tipo_c14070_idx',
        ),
        migrations.RemoveIndex(
            model_name='actividad',
            name='api_activid_estado_24fab6_idx',
        ),
        migrations.RemoveIndex(
            model_name='actividad',
            name='api_activid_fecha_u_75e918_idx',
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='api_cliente_fecha_u_b22749_idx',
        ),
        migrations.RemoveIndex(
            model_name='pedido',
            name='api_pedido_priorid_89fbe6_idx',
        ),

        # ------------------------------------------------------------
        # RENOMBRADO DE ÍNDICES EXISTENTES
        # ------------------------------------------------------------
        migrations.RenameIndex(
            model_name='actividad',
            new_name='idx_act_tenant',
            old_name='api_activid_franqui_a5af5a_idx',
        ),
        migrations.RenameIndex(
            model_name='actividad',
            new_name='idx_act_fechainicio',
            old_name='api_activid_fecha_i_291865_idx',
        ),
        migrations.RenameIndex(
            model_name='actividad',
            new_name='idx_act_fechafin',
            old_name='api_activid_fecha_f_5556aa_idx',
        ),
        migrations.RenameIndex(
            model_name='actividad',
            new_name='idx_act_cliente_fecha',
            old_name='api_activid_cliente_654e8d_idx',
        ),
        migrations.RenameIndex(
            model_name='actividad',
            new_name='idx_act_inmueble_fecha',
            old_name='api_activid_inmuebl_79c7b8_idx',
        ),
        migrations.RenameIndex(
            model_name='actividad',
            new_name='idx_act_pedido_fecha',
            old_name='api_activid_pedido__4cab8f_idx',
        ),
        migrations.RenameIndex(
            model_name='cliente',
            new_name='idx_cliente_tenant',
            old_name='api_cliente_franqui_0cad4e_idx',
        ),
        migrations.RenameIndex(
            model_name='cliente',
            new_name='idx_cliente_nombreact',
            old_name='api_cliente_nombre__130cf0_idx',
        ),
        migrations.RenameIndex(
            model_name='cliente',
            new_name='idx_cliente_nombreact2',
            old_name='api_cliente_nombre__b60095_idx',
        ),
        migrations.RenameIndex(
            model_name='cliente',
            new_name='idx_cliente_email',
            old_name='api_cliente_email_7c88db_idx',
        ),
        migrations.RenameIndex(
            model_name='cliente',
            new_name='idx_cliente_movil',
            old_name='api_cliente_telefon_7485d8_idx',
        ),
        migrations.RenameIndex(
            model_name='edificio',
            new_name='idx_edif_tenant',
            old_name='api_edifici_franqui_986e98_idx',
        ),
        migrations.RenameIndex(
            model_name='edificio',
            new_name='idx_edif_cp',
            old_name='api_edifici_codigo__d5a0f7_idx',
        ),
        migrations.RenameIndex(
            model_name='edificio',
            new_name='idx_edif_prov',
            old_name='api_edifici_provinc_4389a7_idx',
        ),
        migrations.RenameIndex(
            model_name='edificio',
            new_name='idx_edif_tipo',
            old_name='api_edifici_tipo_fi_b1072b_idx',
        ),
        migrations.RenameIndex(
            model_name='edificio',
            new_name='idx_edif_coords',
            old_name='api_edifici_latitud_f9d34b_idx',
        ),
        migrations.RenameIndex(
            model_name='edificio',
            new_name='idx_edif_mod',
            old_name='api_edifici_fecha_u_72b213_idx',
        ),
        migrations.RenameIndex(
            model_name='inmueble',
            new_name='idx_inm_tenant',
            old_name='api_inmuebl_franqui_9a4155_idx',
        ),
        migrations.RenameIndex(
            model_name='pedido',
            new_name='idx_pedido_tenant',
            old_name='api_pedido_franqui_fb6d34_idx',
        ),

        # ------------------------------------------------------------
        # ALTER FIELDS
        # ------------------------------------------------------------
        migrations.AlterField(
            model_name='actividad',
            name='tipo',
            field=models.CharField(
                choices=[
                    ('Contacto genérico', 'Contacto genérico'),
                    ('Llamada genérica', 'Llamada genérica'),
                    ('Contacto directo', 'Contacto directo'),
                    ('Llamada de contacto directo', 'Llamada de contacto directo'),
                    ('Cita de adquisición', 'Cita de adquisición'),
                    ('Llamada de adquisición', 'Llamada de adquisición'),
                    ('Contacto de adquisición', 'Contacto de adquisición'),
                    ('Cita de seguimiento de encargo', 'Cita de seguimiento de encargo'),
                    ('Llamada de seguimiento de encargo', 'Llamada de seguimiento de encargo'),
                    ('Llamada de seguimiento de pedido', 'Llamada de seguimiento de pedido'),
                    ('Contacto de seguimiento de pedido', 'Contacto de seguimiento de pedido'),
                    ('Visita', 'Visita'),
                    ('Reserva', 'Reserva'),
                    ('Propuesta', 'Propuesta'),
                    ('Aceptación de la propuesta', 'Aceptación de la propuesta'),
                    ('Firma contrato de arras', 'Firma contrato de arras'),
                    ('Escritura', 'Escritura'),
                ],
                db_index=True,
                default='Contacto genérico',
                max_length=50,
            ),
        ),

        migrations.AlterField(
            model_name='edificio',
            name='calle',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='numero_calle',
            field=models.CharField(db_index=True, default='S/N', max_length=10),
        ),
        migrations.AlterField(
            model_name='franquicia',
            name='codigo',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='franquicia',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='franquicia',
            name='nombre',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='latitud',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='longitud',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='ref_catastral',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='codigo',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='nombre',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='prioridad',
            field=models.PositiveSmallIntegerField(db_index=True, default=3),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='ubicaciones',
            field=models.TextField(default='', help_text='Zonas separadas por comas'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('superadmin', 'Superadmin'),
                    ('super_coordinador', 'Super Coordinador'),
                    ('franquicia_admin', 'Administrador de Franquicia'),
                    ('oficina_admin', 'Administrador de Oficina'),
                    ('responsable', 'Responsable de Oficina'),
                    ('coordinador', 'Coordinador'),
                    ('comercial', 'Comercial'),
                ],
                db_index=True,
                default='comercial',
                max_length=32,
            ),
        ),

        # ------------------------------------------------------------
        # ÍNDICES NUEVOS
        # ------------------------------------------------------------
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['oficina', 'fecha_inicio'], name='idx_act_oficina_fecha'),
        ),
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['creado_por', 'fecha_inicio'], name='idx_act_user_fecha'),
        ),
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['tipo', 'fecha_inicio'], name='idx_act_tipo_fecha'),
        ),
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['estado', 'fecha_inicio'], name='idx_act_estado_fecha'),
        ),
        migrations.AddIndex(
            model_name='actividad',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['descripcion_empleado'],
                name='idx_act_desc_emp_trgm',
                opclasses=['gin_trgm_ops'],
            ),
        ),
        migrations.AddIndex(
            model_name='actividad',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['descripcion_publica'],
                name='idx_act_desc_pub_trgm',
                opclasses=['gin_trgm_ops'],
            ),
        ),

        # ------------------------------------------------------------
        # 🔥 FIX — GIN index con opclasses correctos
        # ------------------------------------------------------------
        migrations.AddIndex(
            model_name='cliente',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['nombre_apellido'],
                name='idx_cliente_nombre_gin',
                opclasses=['gin_trgm_ops'],
            ),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['nombre_apellidos_completo'],
                name='idx_cliente_nombre2_gin',
                opclasses=['gin_trgm_ops'],
            ),
        ),
        migrations.AddIndex(
            model_name='edificio',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['calle'],
                name='idx_edif_calle_gin',
                opclasses=['gin_trgm_ops'],
            ),
        ),
        migrations.AddIndex(
            model_name='edificio',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['numero_calle'],
                name='idx_edif_numero_gin',
                opclasses=['gin_trgm_ops'],
            ),
        ),

        # ------------------------------------------------------------
        # ÍNDICES DE FRANQUICIA, OFICINA, INMUEBLE, PEDIDO
        # ------------------------------------------------------------
        migrations.AddIndex(
            model_name='franquicia',
            index=models.Index(fields=['codigo'], name='api_franqui_codigo_0c1d9e_idx'),
        ),
        migrations.AddIndex(
            model_name='franquicia',
            index=models.Index(fields=['nombre'], name='api_franqui_nombre_ea0d03_idx'),
        ),
        migrations.AddIndex(
            model_name='franquicia',
            index=models.Index(fields=['creado_en'], name='api_franqui_creado__31428b_idx'),
        ),
        migrations.AddIndex(
            model_name='inmueble',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['direccion_busqueda'],
                name='idx_inm_direccion_trgm',
                opclasses=['gin_trgm_ops'],
            ),
        ),
        migrations.AddIndex(
            model_name='inmueble',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['ref_catastral'],
                name='idx_inm_refcat_trgm',
                opclasses=['gin_trgm_ops'],
            ),
        ),
        migrations.AddIndex(
            model_name='oficina',
            index=models.Index(fields=['franquicia', 'codigo'], name='api_oficina_franqui_d11cc1_idx'),
        ),
        migrations.AddIndex(
            model_name='oficina',
            index=models.Index(fields=['nombre'], name='api_oficina_nombre_bb57c3_idx'),
        ),
        migrations.AddIndex(
            model_name='oficina',
            index=models.Index(fields=['creado_en'], name='api_oficina_creado__080032_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['prioridad', 'tipo_operacion'], name='api_pedido_priorid_e392f3_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['superficie_min', 'superficie_max'], name='api_pedido_superfi_e48626_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['planta_min', 'planta_max'], name='api_pedido_planta__0df60f_idx'),
        ),

        # ------------------------------------------------------------
        # CONSTRAINTS
        # ------------------------------------------------------------
        migrations.AddConstraint(
            model_name='franquicia',
            constraint=models.CheckConstraint(check=models.Q(('codigo', ''), _negated=True), name='franquicia_codigo_no_vacio'),
        ),
        migrations.AddConstraint(
            model_name='oficina',
            constraint=models.CheckConstraint(check=models.Q(('codigo', ''), _negated=True), name='oficina_codigo_no_vacio'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(('role__in', ['oficina_admin', 'responsable', 'coordinador', 'comercial']), _negated=True),
                    ('oficina__isnull', False),
                    _connector='OR'
                ),
                name='usuario_oficina_roles_requieren_oficina'
            ),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(('role', 'franquicia_admin'), _negated=True),
                    ('franquicia__isnull', False),
                    _connector='OR'
                ),
                name='usuario_franquicia_admin_requiere_franquicia'
            ),
        ),
    ]
