# Generated by Django 4.2.13 on 2025-12-08 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_franquicia_options_alter_oficina_options_and_more'),
    ]

    operations = [
    ]
