# Generated by Django 4.2.13 on 2025-12-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20251208_2348'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pedido',
            name='pedido_superficie_min_le_max',
        ),
        migrations.RemoveConstraint(
            model_name='pedido',
            name='pedido_planta_min_le_max',
        ),
        migrations.RemoveConstraint(
            model_name='pedido',
            name='pedido_precio_min_le_max',
        ),
        migrations.RemoveConstraint(
            model_name='pedido',
            name='pedido_rentabilidad_min_le_max_or_zero',
        ),
        migrations.RemoveIndex(
            model_name='actividad',
            name='idx_act_desc_emp_trgm',
        ),
        migrations.RemoveIndex(
            model_name='actividad',
            name='idx_act_desc_pub_trgm',
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='idx_cliente_nombre_gin',
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='idx_cliente_nombre2_gin',
        ),
        migrations.RemoveIndex(
            model_name='edificio',
            name='idx_edif_calle_gin',
        ),
        migrations.RemoveIndex(
            model_name='edificio',
            name='idx_edif_numero_gin',
        ),
        migrations.RemoveIndex(
            model_name='inmueble',
            name='idx_inm_direccion_trgm',
        ),
        migrations.RemoveIndex(
            model_name='inmueble',
            name='idx_inm_refcat_trgm',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='api_user_role_9b9076_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['franquicia'], name='api_user_franqui_ead34f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['oficina'], name='api_user_oficina_f75238_idx'),
        ),
    ]
