# Generated by Django 4.2.13 on 2025-12-08 22:58
from django.db import migrations, models
import django


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_pedido_pedido_superficie_min_le_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
