# Generated by Django 4.2.13 on 2025-12-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20251208_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='tipo',
            field=models.CharField(choices=[('Contacto genérico', 'Contacto genérico'), ('Llamada genérica', 'Llamada genérica'), ('Contacto directo', 'Contacto directo'), ('Llamada de contacto directo', 'Llamada de contacto directo'), ('Cita de adquisición', 'Cita de adquisición'), ('Llamada de adquisición', 'Llamada de adquisición'), ('Contacto de adquisición', 'Contacto de adquisición'), ('Cita de seguimiento de encargo', 'Cita de seguimiento de encargo'), ('Llamada de seguimiento de encargo', 'Llamada de seguimiento de encargo'), ('Llamada de seguimiento de pedido', 'Llamada de seguimiento de pedido'), ('Contacto de seguimiento de pedido', 'Contacto de seguimiento de pedido'), ('Visita', 'Visita'), ('Reserva', 'Reserva'), ('Propuesta', 'Propuesta'), ('Aceptación de la propuesta', 'Aceptación de la propuesta'), ('Firma contrato de arras', 'Firma contrato de arras'), ('Escritura', 'Escritura'), ('Reunión', 'Reunión'), ('Actividad genérica', 'Actividad genérica'), ('Zona', 'Zona')], db_index=True, default='Contacto genérico', max_length=50),
        ),
    ]
